### ISSUE TITLE
PHL ADM0 is low quality

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/gbRelease#120]
We need to improve the quality of PHL ADM0:
https://www.geoboundaries.org/data/geoBoundaries-3_0_0/PHL/ADM0/geoBoundariesPreview-3_0_0-PHL-ADM0.png

**Comment by dickoa** [comment]
Hi @DanRunfola,

The new version of this dataset on HDX is more accurate and I hope that we will find a version with open license that accurate too

![phl_adm0](https://user-images.githubusercontent.com/500140/92463982-05b33e00-f1bc-11ea-9be1-40b8a0b69791.png)

Ahmadou

**Comment by DanRunfola** [comment]
Perfect - for your awareness, we're moving to a three-prong release
strategy with gbOpen, gbHumanitarian, and gbAuthoritative, which will all
have different license requirements.  This would fit right in to
gbHumanitarian.  We're also going to be working with HDX to try and
automatically pull the UN OCHA shapes for the Humanitarian release, though
things have been slow on that front.

**Comment by dickoa** [comment]
Thanks @DanRunfola and let me know if I can help on that HDX integration. They have a  great Python API so I'm sure, with their support, we will find a good workflow to access their data directly. I had a R package R to automatically read (working on writing too?) data from HDX.https://gitlab.com/dickoa/rhdx
I would to alpha/beta test the new API to quickly adapt {rgeoboundaries} let me know when that might possible (if possible).
Thanks a lot!

**Comment by DanRunfola** [comment]
This is very helpful - a simple way to do this (As a test) would be a
python script that fires ~once an evening and checks if the HDX dataset has
updated.  If it has, have that same script package the shapefile and
create  PR with it.

Note I am also likely to update our PR process soon - i.e., right now a
user has to update in two places (a master metadata spreadsheet and a zip
file with a *.shp).  Ultimately I would like that to be just a single zip
file that contains valid metadata information.  So, maybe after I implement
that (~a month out) I'll ping on this and we can get it implemented?

**Comment by nmspage** [comment]
This issue is closed with PR #858
