### ISSUE TITLE
Large GeoJSON files leading to "GeoJSON object too complex errors"

### ISSUE THREAD

**Issue by rexdouglass** [wmgeolab/gbRelease#14]
The following files create loading problems for SF
"geoBoundaries-2_0_1-CAN-ADM0.geojson" "geoBoundaries-2_0_1-CAN-ADM1.geojson" "geoBoundaries-2_0_1-CAN-ADM2.geojson" "geoBoundaries-2_0_1-CAN-ADM3.geojson" "geoBoundaries-2_0_1-CHL-ADM0.geojson" "geoBoundaries-2_0_1-GBR-ADM0.geojson" "geoBoundaries-2_0_1-HUN-ADM3.geojson" "geoBoundaries-2_0_1-JPN-ADM0.geojson" "geoBoundaries-2_0_1-NOR-ADM0.geojson" "geoBoundaries-2_0_1-NZL-ADM0.geojson"
"geoBoundaries-2_0_1-PHL-ADM0.geojson" "geoBoundaries-2_0_1-PHL-ADM1.geojson"

After a whole day of updating packages, R to 4.0, ubuntu to 20.0 I've been able to move from straight crashes to a printable warning of 
"GDAL Error 1: GeoJSON object too complex, please see the OGR_GEOJSON_MAX_OBJ_SIZE environment option"

In R console this will work

```
> library(sf)
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
> temp <-  "https://www.geoboundaries.org/data/geoBoundaries-2_0_1/CAN/ADM0/geoBoundaries-2_0_1-CAN-ADM0.geojson" %>% st_read()
Reading layer `geoBoundaries-2_0_1-CAN-ADM0' from data source `https://www.geoboundaries.org/data/geoBoundaries-2_0_1/CAN/ADM0/geoBoundaries-2_0_1-CAN-ADM0.geojson' using driver `GeoJSON'
Simple feature collection with 1 feature and 5 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -141.0181 ymin: 41.68144 xmax: -52.61941 ymax: 83.1355
geographic CRS: WGS 84
> 
```

In rstudio, it slows to a crawl because it's throwing thousands of warnings and usually fails outright.

I haven't resolved this problem yet but I wanted to flag it for others.

```

> library(sf)
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.9-3

loaded via a namespace (and not attached):
 [1] compiler_4.0.0     magrittr_1.5       class_7.3-17       DBI_1.1.0          tools_4.0.0        units_0.6-6        Rcpp_1.0.4.6       KernSmooth_2.23-17 grid_4.0.0         e1071_1.7-3        classInt_0.4-3    
```

**Comment by DanRunfola** [comment]
So - good news on this, I think.  geoBoundaries 3.0.0 should be coming out by the end of May (i.e., the next few days), and we will be including a simplified version of geoBoundaries that is easier to use, while losing relatively little precision.   Most boundaries see a reduction of around 50 - 85% file size in this secondary product.

Also - Canada is an absolute beast in terms of it's underlying data precision.  Here's the quick preview from the new build coming:
![image](https://user-images.githubusercontent.com/7882645/83220086-0e699200-a140-11ea-9759-7d2c0ce1d822.png)

**Comment by DanRunfola** [comment]
So - even better news.  This post encouraged me to spend some time (i.e., all night 👍 ) optimizing the simplification algorithm.  Ireland ADM2 seems to be the one boundary escaping a reasonable simplification (it's still a reduction of nearly 50%, but that means 30 megs!). Some previews:
![image](https://user-images.githubusercontent.com/7882645/83273638-bb70f880-a19a-11ea-8362-8590ab6a1668.png)
![image](https://user-images.githubusercontent.com/7882645/83273665-c592f700-a19a-11ea-8659-7682ae3ba9d1.png)
![image](https://user-images.githubusercontent.com/7882645/83273691-d04d8c00-a19a-11ea-8bf6-699156065d10.png)
![image](https://user-images.githubusercontent.com/7882645/83273805-ece9c400-a19a-11ea-86d5-feddb68f2be7.png)

**Comment by DanRunfola** [comment]
Alright - new version just went live.  Could you confirm if using this URL:

https://www.geoboundaries.org/data/geoBoundaries-3_0_0/CAN/ADM0/geoBoundaries-3_0_0-CAN-ADM0.geojson

provides a workaround?

**Comment by rexdouglass** [comment]
Confirmed the new file loads, and loads FAST. Thank you so much.

```
> library(sf)
> library(tictoc)
> tic()
> temp <-  "https://www.geoboundaries.org/data/geoBoundaries-3_0_0/CAN/ADM0/geoBoundaries-3_0_0-CAN-ADM0.geojson" %>% st_read()
Reading layer `geoBoundaries-3_0_0-CAN-ADM0' from data source `https://www.geoboundaries.org/data/geoBoundaries-3_0_0/CAN/ADM0/geoBoundaries-3_0_0-CAN-ADM0.geojson' using driver `GeoJSON'
Simple feature collection with 1 feature and 5 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -141.0027 ymin: 41.68116 xmax: -52.61937 ymax: 83.14457
geographic CRS: WGS 84
> toc()
2.394 sec elapsed
```

**Comment by DanRunfola** [comment]
Awesome!  I'm going to close this out for now, then, even though the original problem will still arise.  For anyone that stumbles on this, the solution is to upgrade to our 3.0.0 release product.
