### ISSUE TITLE
gBOPEN - BFA ADM 4

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/gbRelease#148]
It is possible that ADM 4 (urban communes) exist in Burkina Faso.

**Comment by lydiatroup** [comment]
ADM 4 does not exist in Burkina Faso. Two ADM3s (Ouagadougou and Bobo-Dioulasso) are further divided, however these divisions are purely used for election purposes, and no administrative ones. See pages 52- 58 of the [following document](https://openknowledge.worldbank.org/handle/10986/12235v)
