### ISSUE TITLE
gBOPEN - AGO ADM 4

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/gbRelease#152]
It is possible that ADM 4 (and possibly more granular ADMs) exists in Angola.

**Comment by memulder** [comment]
It does not look like anything past ADM 3 exists for Angola. I checked out the sources that indicated their might be an ADM 4, but it seems like past the communes (ADM 3) there are only further divisions (cities/neighborhoods/villages) that have no administrative powers and the constitution only has three ADM levels outlined as well.

**Comment by slfuhrig** [comment]
Since we cannot find any sources indicating the presence of an ADM 4, we will close this issue.
