### ISSUE TITLE
gBOPEN NRU ADM 2 metadata

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/gbRelease#165]
We have a gB OPEN shapefile for NRU ADM 2, but no metadata information is listed. So, we need to check the raw records to find the information to add to the gB OPEN metadata csv. If no records are found, we will need a new shapefile.

**Comment by sylviashea1** [comment]
File listed as NRU_ADM2 may actually be ADM1.

**Comment by sylviashea1** [comment]
New boundary needed for NRU ADM 2. Current boundary is incorrect.
