### ISSUE TITLE
MUS ADM1 / ADM0 Disagreement

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/gbRelease#19]
Mauritius has a large disagreement in our source data between the ADM0 and ADM1 boundaries.  For a future release, we should attempt to identify an authoritative source.  We also need to be specific in that we are mapping *land* boundaries, not sea, which may have other ramifications across our dataset.

**Comment by nmspage** [comment]
![Discrepancy_ADM0_ADM1](https://user-images.githubusercontent.com/68017504/88993306-8de81e80-d2b3-11ea-998b-6e694b3ccb1f.PNG)

It appears that ADM 1 is missing two islands to the north of Mauritius. I will extract those features and add them to ADM 1.
