### ISSUE TITLE
PHL ADM 1/2/3 coastline discrepancies

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/gbRelease#27]
ADMs 1, 2, and 3 for the Philippines are all generally very similar, yet at a granular level the coastlines of these boundaries do not match in some areas. This issue is likely due to differences in data collection given that they all come from the same source. Newer and more standardized boundaries may need to be collected in the future.

**Comment by DanRunfola** [comment]
Of note, we are considering a satellite-imagery based solution to this issue that could be applied uniformly across all data.  TBD.
