### ISSUE TITLE
Create 'nesting' ID for administrative hierarchies

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/gbRelease#5]
We are planning on the creation of a 'nesting' ID for administrative hierarchies.  This would only be released as a part of our global / unified data products (i.e., those that are designed to provide cross-country topological validity based on a third party ADM0 dataset).  This would provide better compatibility with other products out there (like GADM).

Current thoughts on this:
A) For every administrative boundary less than ADM0 (i.e., ADM1 - ADM5), calculate the centroid.

B) If the centroid is not contained by the polygon, move the centroid to the nearest point that would be contained by the polgyon.

C) For each higher administrative boundary (ADM2 would search through ADM1 and ADM0, for example), identify the geoBoundary shapeID that the centroid falls within (i.e., "AUS-ADM1-2_0_0-B2").  This would allow lookups of the appropriate shapes at higher levels of the hierarchy.

D) Add this shapeID to a column indicating the ADM hierarchy it belongs to, and add one metafield for easier parsing - i.e., a row might look something like:
```
Column - Value
shapeID - AUS-ADM2-2_0_0-B2    
ADM1- AUS-ADM1-2_0_0-B3
ADM0 -  AUS-ADM0-2_0_0-B1
ALLADM - AUS-ADM1-2_0_0-B3|AUS-ADM0-2_0_0-B1                             
```

**Comment by logoul** [comment]
Hi, this is Liza Logounova from WRI. Just to confirm, there is currently no single field in the dataset that represents a unique ID which contains both that boundary value and values of all nested boundaries. Looks like ALLADM in the example above doesn't include ADM2 ID.

**Comment by DanRunfola** [comment]
Oh - interesting, so you would *also* want the boundary ID for the row itself copied into the "ALL" field, i.e.:
Column - Value
shapeID - AUS-ADM2-2_0_0-B2    
ADM1- AUS-ADM1-2_0_0-B3
ADM0 -  AUS-ADM0-2_0_0-B1
ALLADM - AUS-ADM2-2_0_0-B2|AUS-ADM1-2_0_0-B3|AUS-ADM0-2_0_0-B1  

Something like the above?

**Comment by logoul** [comment]
Yes, exactly, I believe developers from one of the team requested that.

**Comment by DanRunfola** [comment]
Can do - that will be very easy to add.

**Comment by logoul** [comment]
Also, I believe we were only expecting up to ADM 2. Are you also going to provide details up to ADM 5?

**Comment by DanRunfola** [comment]
This might get to a slightly broader question: what we currently plan on doing is releasing 5 different shapefiles, one for each ADM (0, 1, 2, 3, 4 and 5).  Within each of those shapefiles (or geoJsons, etc), we'll have the fields detailed above; for ADM5 we would have all of the ADM4, 3, 2, 1, and 0; for ADM4 we would have all of the ADM 3, 2, 1....  etc.  

We could create one gigantic shapefile with all ADM levels (0-5), but my primary concern about that would be the physical size of the data (and, related to that, our ability to distribute exceptionally large files).  If I had to guess, something like that would probably be in the 200-500 GB range for a single file.  If ya'll needed that for something it wouldn't be hard to produce (literally just merging the 5 independent layers), but I wouldn't want to do it unless it has an immediate use case.

**Comment by DanRunfola** [comment]
One thought on the above - we could do the unified (ADM0-5) release for the simplified set of polygons, which would dramatically reduce the total file size as well.

**Comment by logoul** [comment]
Hi Dan, for WRI we will need only from ADM0-ADM2. So your original approach will work.

**Comment by logoul** [comment]
Hi Dan, we will definitely need simplified shapes for ADM0-ADM2. 
Just to summarize requirements here.
Ideally, we would need:
1) Shapefile with simplified shapes globally 
2) Each geoboundary shape should have a unique ID that represens information about that shape and all nested shapes above (aka your ALLADM)
3) All boudnaries should be based on the UN guidelines and there should be no overlap

**Comment by DanRunfola** [comment]
Yep - all sounds good.  I think the only thing I'm left wondering about is if - for your systems - it's ok for ADM0 - ADM2 to be released in 3 different files (i.e., ADM0.geojson; ADM1.geojson; ADM2.geojson), or if you need one master ("ADM_0_2.geojson").

The three different files approach would still have all of the same information - it's literally just broken into the three subsets.  On our end, that's much easier to distribute because the file size for individual ADM layers stays more reasonable.

**Comment by logoul** [comment]
Hi Dan, I think three files are OK. Thank you so much for being so responsive to our needs!

**Comment by DanRunfola** [comment]
Ya'll found us at a very good time, when we all happen to be locked inside with nothing to do but code ;)

**Comment by DanRunfola** [comment]
Done in 3.0 release!
