### ISSUE TITLE
Update GHA_ADM2 in gbOpen

### ISSUE THREAD

**Issue by sylviashea1** [wmgeolab/gbRelease#641]
The current gbOpen GHA_ADM2 boundary from 2007 is now out of date (districts have been added/moved). A new GHA_ADM2 shapefile is needed.

Things to keep in mind:
• Because the updates are new, the shapefile will probably need to be digitized. 
• [Here](http://www.ghanadistricts.com/Home/AllDistricts) is the list of ADM2 attributes in Ghana
• [Here](https://en.wikipedia.org/wiki/Districts_of_Ghana#/media/File:Ghana_districts.png) is a CC png of the updated shapes for Ghana ADM2

**Comment by dickoa** [comment]
Hi @sylviashea1 

I have access to up to date GHA ADM2 boundaries from Ghana National Statistics Office shared through an USAID project here:

https://hub.arcgis.com/datasets/USAID-Ghana-HPNO::ghana-new-260-district/data?geometry=-14.962%2C4.146%2C12.900%2C11.757

I hope we might be able to add this to gbOpen!

Ahmadou

**Comment by slfuhrig** [comment]
Ahmadou thank you so much for sharing! We'll have someone look into this further to see if we can find license information that is compatible for gbOpen. It may also be a candidate for gbAuthoritative. 

Sydney
